### ISSUE TITLE
关于模型数据预处理及模型输入的问题？

### ISSUE THREAD

**Issue by YeNiTing** [padeoe/cail2019#19]
在运行data.py后会得到文件夹data，其中子文件夹raw、test、train，请问在train.py中
    # TRAINING_DATASET = 'data/train/input.txt'  # for quick dev
    TRAINING_DATASET = "data/raw/CAIL2019-SCM-big/SCM_5k.json"

其中training_dataset 的选择会影响模型的训练吗？./data/train下的input.txt与原始SCM_5k.json有什么不同吗？

**Comment by padeoe** [comment]
对了，这点我没说清。关系是：

`raw` = `train` + `data`。

这句代码用的是raw：`TRAINING_DATASET = "data/raw/CAIL2019-SCM-big/SCM_5k.json"`
这句代码用的是train：`TRAINING_DATASET = 'data/train/input.txt'`

我把用raw的注释掉了，默认用train数据且kfold=1`时，此时会用train数据训练，然后用test数据测试，这样可以快速测试模型性能，**仅训练1次、测试一次**。

如果把kfold设置为大于1的数字，这时候会运行k折交叉验证，此时可以用raw数据，代码会对所有数据自行划分训练集、测试集来评估模型性能，**训练k次、测试k次**。
