### ISSUE TITLE
数据label问题

### ISSUE THREAD

**Issue by bugmaker00** [padeoe/cail2019#20]
作者您好，感谢您的分享。
在看数据增广部分时，发现这样一个问题，您在增广时默认B为标签值，即sim（AB）>sim（AC），但是我观察到下载的数据集中每条json数据是有“label”标签的，且“label”标签存在B和C两种，这样是不是和您的预设冲突了呢？
期待您的回复~

**Comment by padeoe** [comment]
欸，我看了下，主办方改了数据格式了...比赛数据集没有label字段，如你所说“默认B为标签值，即sim（AB）>sim（AC）”，现在既然加了label字段，得改一下代码了

**Comment by bugmaker00** [comment]
嗯嗯，多谢作者确认！我去对应改一下代码。
另外您那边还存有比赛时无label字段的数据吗，有的话可以分享下嘛，我想跑一下您的代码看看结果~谢谢。
bitdongbo@163.com

**Comment by padeoe** [comment]
已发

**Comment by maicai** [comment]
作者您好，我用data.py下载的数据集有‘label’字段，训练的acc和测试的acc都差不多在0.59左右(batch_size=4, k = 1)。看到这里才知道是‘label’字段的影响，请问您可以分享一份无label字段的数据吗，也想看一下这个的效果，谢谢您~  815517522@qq.com
![train_1](https://user-images.githubusercontent.com/20392702/109251606-b83c9300-7826-11eb-9675-907add2536d1.png)

**Comment by padeoe** [comment]
@maicai 5f8d901 已经修改代码适配最新数据集格式
