### ISSUE TITLE
启发式增广的代码有错误

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [padeoe/cail2019#21]
对于标签为C的数据，代码中(model.py)的启发式增广如下
pd.Series((x["C"], x["A"], x["B"], "C"))

但是我认为正确的应该是
pd.Series(x["C", x["B"], x["A"], "C"))

同理，对于启发式+反对称式的增广，代码也有问题

**Comment by padeoe** [comment]
c91c236 已修复 。因为主办方更新了数据集格式，前段时间更新代码引入的错误。感谢~
