### ISSUE TITLE
作者您好！请问我该如何下载pytorch版本的BERT预训练模型呢？不胜感激！

### ISSUE THREAD

**Issue by YZW-explorer** [padeoe/cail2019#24]
作者您好！请问我该如何下载pytorch版本的BERT预训练模型呢？不胜感激！

**Comment by padeoe** [comment]
从 google/bert 的页面下载 [tf版本](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip)的模型，然后使用 huggingface/transformers 的[转换脚本](https://huggingface.co/transformers/converting_tensorflow_models.html)转为 pytorch 版本的模型。

嫌麻烦也可以直接在 [https://huggingface.co/bert-base-chinese/tree/main](https://huggingface.co/bert-base-chinese/tree/main) 下载转换好的模型（`pytorch_model.bin`、`vocab.txt`、`config.json` 三个文件）。

**Comment by YZW-explorer** [comment]
好嘞谢谢啦！
