### ISSUE TITLE
from apex import FP16 rasied errors

### ISSUE THREAD

**Issue by bruce1408** [padeoe/cail2019#7]

**Comment by bruce1408** [comment]
env:
```
ubuntu 16.04
pytorch=1.1.0
cuda:10.0.130
apex=0.1
GPU 2080Ti x 4
```
when i run the code ,the error raised as follows
```
2019-11-04 23:26:20 - train model - INFO - config: {
    "batch_size": 12,
    "epochs": 2,
    "fp16": true,
    "learning_rate": 2e-05,
    "max_length": 512
}
Traceback (most recent call last):
  File "model.py", line 683, in <module>
    trainer.train(MODEL_DIR, 1)
  File "model.py", line 383, in train
    from apex.optimizers import FP16_Optimizer
ImportError: cannot import name 'FP16_Optimizer'
```
**can not import name FP16_Optimizer**, so i change the fp16 to false,and it works fun。

**Comment by padeoe** [comment]
the latest apex version changed the api, for now, you can use old apex version from its git repo. I will update the code soon.

**Comment by bruce1408** [comment]
> the latest apex version changed the api, for now, you can use old apex version from its git repo. I will update the code soon.

thx， i will watch on your work at all times !

**Comment by padeoe** [comment]
Hi, I have updated the [README](https://github.com/padeoe/cail2019#%E8%BD%AF%E4%BB%B6%E4%BE%9D%E8%B5%96) on apex installation for quick fix. The codes using latest apex is under development, I will close this issue when it's released.

**Comment by bruce1408** [comment]
> Hi, I have updated the [README](https://github.com/padeoe/cail2019#%E8%BD%AF%E4%BB%B6%E4%BE%9D%E8%B5%96) on apex installation for quick fix. The codes using latest apex is under development, I will close this issue when it's released.

OK，think you for sharing your code and update the code, i have learn lot from your project!

**Comment by padeoe** [comment]
The codes has been updated from huggingface/pytorch_pretrained_bert to **huggingface/transformers**, if you install latest apex, no errors now. Cheers!
